name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

      version:
        description: 'Select the version'
        required: true
        default: 'v1.0'
        type: choice
        options:
          - v1.0
          - v1.1
          - v2.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print input values
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
